EVAL_QUERIES = [
    "What is photosynthesis?",
    "Explain how plants make food.",
    "Why do plants need sunlight?",
    "Who was Albert Einstein?",
    "What did Einstein contribute to physics?",
    "What is the theory of relativity?",
    "What caused World War II?",
    "Reasons behind the Second World War",
    "Why did WW2 happen?",
    "What is gravity?",
    "Explain gravitational force",
    "Why do objects fall to Earth?",
    "How do volcanoes form?",
    "What causes volcanic eruptions?",
    "Explain formation of volcanoes",
    "What is DNA?",
    "What is the structure of DNA?",
    "Why is DNA important?",
    "What is the speed of light?",
    "How fast does light travel?",
    "Explain speed of light",
    "What is machine learning?",
    "Define machine learning",
    "How do computers learn from data?",
    "What is the capital of France?",
    "Which city is capital of France?",
    "Where is Paris located?",
    "How does electricity work?",
    "What is electric current?",
    "Explain flow of electricity",
    "What is the human heart?",
    "How does the heart function?",
    "Role of heart in human body",
    "What is climate change?",
    "What causes global warming?",
    "Explain climate change effects",
    "Who was Isaac Newton?",
    "What are Newton’s laws?",
    "Explain Newton’s contribution",
    "What is an atom?",
    "What are atoms made of?",
    "Structure of atom",
    "How do airplanes fly?",
    "Principle of flight",
    "Why planes stay in air",
    "What is democracy?",
    "Explain democratic system",
    "What are democratic principles",
    "What is the solar system?",
    "Planets in solar system",
    "Structure of solar system",
    "What are bacteria?",
    "Define bacteria",
    "Are bacteria harmful?",
    "What is evolution?",
    "Explain theory of evolution",
    "Darwin’s theory summary",
    "How does the internet work?",
    "Explain internet basics",
    "How data travels online",
    "What is artificial intelligence?",
    "Define AI",
    "Applications of AI",
    "What is blockchain?",
    "How blockchain works",
    "Use cases of blockchain",
    "What is cryptocurrency?",
    "Explain Bitcoin",
    "How crypto works",
    "What is inflation?",
    "Why do prices increase?",
    "Effects of inflation",
    "What is supply and demand?",
    "Explain economic supply demand",
    "How markets work",
    "What is photosynthesis equation?",
    "Explain oxygen cycle",
    "What is water cycle?",
    "Stages of water cycle",
    "How evaporation works",
    "What is a black hole?",
    "Explain black holes",
    "How black holes form",
    "What is quantum mechanics?",
    "Basics of quantum physics",
    "Explain quantum theory",
    "What is renewable energy?",
    "Examples of renewable energy",
    "Benefits of renewable energy",
    "What is fossil fuel?",
    "Types of fossil fuels",
    "Environmental impact of fossil fuels",
    "What is the human brain?",
    "Functions of brain",
    "How brain works",
    "What is metabolism?",
    "Explain metabolic process",
    "Why metabolism matters",
    "What is photosynthesis in simple terms?",
    "Explain plant energy conversion",
    "What is gravity in simple words?",
    "Explain falling objects",
    "What is magnetism?",
    "How magnets work",
    "Explain magnetic field",
    "What is electricity generation?",
    "How power plants work",
    "Sources of electricity",
    "What is cloud computing?",
    "Explain cloud services",
    "Benefits of cloud computing",
    "What is operating system?",
    "Role of OS",
    "Examples of operating systems",
    "What is CPU?",
    "How processor works",
    "Explain central processing unit",
    "What is RAM?",
    "Difference between RAM and storage",
    "Why memory is important",
    "What is database?",
    "Types of databases",
    "Explain relational database",
    "What is SQL?",
    "How SQL works",
    "Uses of SQL",
    "What is networking?",
    "Basics of computer networks",
    "Explain TCP/IP",
    "What is cybersecurity?",
    "Importance of security",
    "Types of cyber attacks",
    "What is encryption?",
    "How encryption works",
    "Purpose of encryption",
    "What is HTTP?",
    "How web works",
    "Explain HTTP protocol",
    "What is API?",
    "How APIs work",
    "Examples of APIs",
    "What is data science?",
    "Role of data scientist",
    "Explain data analysis",
    "What is big data?",
    "Characteristics of big data",
    "Examples of big data",
    "What is Hadoop?",
    "Explain Hadoop ecosystem",
    "Uses of Hadoop",
    "What is Spark?",
    "How Apache Spark works",
    "Advantages of Spark",
    "What is Kubernetes?",
    "Explain container orchestration",
    "Uses of Kubernetes",
    "What is Docker?",
    "How Docker works",
    "Benefits of containers",
    "What is DevOps?",
    "Explain DevOps practices",
    "Benefits of DevOps",
    "What is CI/CD?",
    "Explain continuous integration",
    "Benefits of CI/CD",
    "What is load balancing?",
    "How load balancer works",
    "Importance of load balancing",
    "What is caching?",
    "Why caching improves performance",
    "Types of caching",
    "What is latency?",
    "Difference between latency and throughput",
    "Why latency matters",
    "What is throughput?",
    "Explain system throughput",
    "How to improve throughput",
    "What is distributed system?",
    "Examples of distributed systems",
    "Challenges in distributed systems",
    "What is consistency in databases?",
    "Explain CAP theorem",
    "Consistency vs availability",
    "What is replication?",
    "Types of replication",
    "Benefits of replication",
    "What is sharding?",
    "Explain database sharding",
    "When to shard data",
    "What is indexing?",
    "How indexes improve performance",
    "Types of indexing",
    "What is vector database?",
    "How vector search works",
    "Use cases of vector DB",
    "What is RAG?",
    "Explain retrieval augmented generation",
    "Why RAG is useful",
]